[project]
name = "project-2-yaroshchuk-m-26-555"
version = "0.1.0"
description = ""
authors = [
    { name = "Yva09" }
]
requires-python = ">=3.14"
dependencies = []

[tool.poetry]
packages = [
    { include = "src" },
]

[tool.poetry.scripts]
project = "src.primitive_db.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"